body:
  - type: checkbox
    attributes:
      name: show_help_api
      label: "show api" 
      defaultValue: true

  - type: checkbox
    attributes:
      name: show_help_switch
      label: "show switch"
      defaultValue: true

  - type: checkbox
    attributes:
      name: show_help_status
      label: "show status"
      defaultValue: true

  - type: checkbox
    attributes:
      name: show_help_wishlist
      label: "show wishlist"
      defaultValue: true

  - type: checkbox
    attributes:
      name: show_help_settings
      label: "show settings"
      defaultValue: true

  - type: checkbox
    attributes:
      name: show_help_restart
      label: "show restart"
      defaultValue: true

  - type: checkbox
    attributes:
      name: show_help_exit
      label: "show exit"
      defaultValue: true

  - type: checkbox
    attributes:
      name: show_help_clear
      label: "show clear"
      defaultValue: true

  - type: input
    attributes:
      name: settings_tree_opener_exe
      label: "open `tree.md` with preferred app"
      description: "full path to an editor/viewer exe"
      defaultValue: ""

  - type: input
    attributes:
      name: blacklisted_app_ids
      label: "hidden apps"
      description: "comma separated list of app ids to hide\ne.g. 730 = cs2"
      defaultValue: "730"

  - type: checkbox
    attributes:
      name: enable_perf_logging
      label: "[debug] enable performance logging"
      description: "log slow query stages & network calls to plugin_steamflow.log"
      defaultValue: false
